spring:
  application:
    name: NegotiatorBot
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: dev

  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        region: eu-central-1
        endpoint: http://127.0.0.1:9000/
        bucket-name: bucket1

logging:
  level:
    org:
      springframework:
        security: DEBUG

telegram:
  token: 1234

open-ai:
  token: ${OPEN_AI_TOKEN}
  assistant:
    model: gpt-3.5-turbo
    instructions: you are assistant for explaining files content
    
dadata:
  url: http://suggestions.dadata.ru/suggestions/api/4_1/rs
  token: ${DADATA_TOKEN}

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres_user
    password: postgres_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/mydb_prod  # URL для базы данных в prod
    username: produser
    password: prodpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false