spring:
  application:
    name: NegotiatorBot
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: dev

logging:
  level:
    org:
      springframework:
        security: DEBUG

telegram:
  token: 1234

open-ai:
  token: ${OPEN_AI_TOKEN}
  assistant:
    model: gpt-3.5-turbo
    instructions: ${OPEN_AI_INSTRUCTION}

dadata:
  url: ${DADATA_URL}
  token: ${DADATA_TOKEN}

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        region: ${S3_REGION}
        endpoint: ${S3_ENDPOINT}
        bucket-name: ${S3_BUCKET_NAME}

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        region: ${S3_REGION}
        endpoint: ${S3_ENDPOINT}
        bucket-name: ${S3_BUCKET_NAME}