spring:
  application:
    name: Negotiation-App
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: dev
  jpa:
    open-in-view: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    default-schema: app
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false

logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG

telegram:
  token: 1234

open-ai:
  token: ${OPEN_AI_TOKEN}
  assistant:
    model: gpt-3.5-turbo
    instructions: ${OPEN_AI_INSTRUCTION}

dadata:
  url: ${DADATA_URL}
  token: ${DADATA_TOKEN}

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        region: ${S3_REGION}
        endpoint: ${S3_ENDPOINT}
        bucket-name: ${S3_BUCKET_NAME}

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        region: ${S3_REGION}
        endpoint: ${S3_ENDPOINT}
        bucket-name: ${S3_BUCKET_NAME}