spring:
  application:
    name: NegotiatorBot

  profiles:
    active: dev

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

telegram:
  token: 1234

open-ai:
  token: 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
  assistant:
    model: gpt-3.5-turbo
    instructions: you are assistant for explaining files content

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres_user
    password: postgres_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/mydb_prod  # URL для базы данных в prod
    username: produser
    password: prodpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false